services:
  fotstat_go:
    restart: always
    build: .
    platform: linux/amd64
    image: kobums/fotstat_go:latest
    container_name: fotstat_go
    ports:
      - "8009:8009"
    env_file:
      - .env.yml
    volumes:
      - ./webdata:/root/webdata
